### ISSUE TITLE
Nav weights does not work for pages.

### ISSUE THREAD

**Issue by General-101** [HEInventions/docnado#56]
Nav weights do not seem to sort pages. They also seem to cause issues with the currently highlighted page on the nav bar.

![nav_bar_no_weight](https://user-images.githubusercontent.com/23564623/101740742-d815b380-3a8e-11eb-8665-0b3ef2cd506a.png)

`nav:        Halo 1 __0__>H1 Model Guides __3__>H1 JMS __0__>H1 Export __0__>My First H1 Model`

![nav_bar_weights](https://user-images.githubusercontent.com/23564623/101740890-05626180-3a8f-11eb-86fc-75e663a594b3.png)

`nav:        Halo 1 __0__>H1 Model Guides __3__>H1 JMS __0__>H1 Export __0__>My First H1 Model __0__`

**Comment by ghost** [comment]
Hi, General-101 ,
Thank you for your feedback, sorry it took so long to get back to you.

The nav-weights feature doesn't sort fields into their explicit order, it "weighs" them to be in certain positions. For example a nav-string with a high number eg `__10__` will appear BELOW a field with a low nav string eg `__0__ ` or `__1__`.

We don't currently have explicit nav ordering in order to solve the issue of number colissions. If two pages are labeled with the same number they will go next to each other. 

One thing to be certain about is that the nav weights are set on the first nav docstring encountered, for example if you have two pages ajacent to each other with the docstrings:

` Halo 1 __0__>H1 Model Guides __3__>H1 JMS __0__>H1 Export __0__>My First H1 Model __0__`
and
` Halo 1 __5__>H1 Model Guides __3__>H1 JMS __0__>H1 Export __0__>My First H1 Model __0__`

The postition of the "Halo 1" field would depend upon which ever one was encountered first. It is important to make sure that your docstrings are consistant across your project.

Also it is important to note that the navigation ordering is not dynamically reloaded (this is a feature that we intend to add in the future). If you make changes to the navigation ordering you must close your docnado application and relaunch it.
